# Generated by Django 5.0 on 2024-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='cuit',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
