# Generated by Django 5.0 on 2024-01-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organismo', '0002_alter_organismo_cuit'),
        ('organismo', '0002_organismo_fecha_actualizacion_alter_organismo_cuit'),
    ]

    operations = [
    ]
