# Generated by Django 5.0 on 2024-01-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='auth_user',
        ),
    ]
