# Generated by Django 5.0 on 2024-01-03 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas_a_publicar', models.DateField()),
            ],
            options={
                'verbose_name': 'Fecha',
                'verbose_name_plural': 'Fechas',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('inicado', 'iniciado'), ('pendiente_pago', 'pendiente_pago'), ('pendiente_revision_pago', 'pendiente_revision_pago'), ('aprobado', 'aprobado'), ('publicado', 'publicado'), ('rechazado', 'rechazado')], default='iniciado')),
                ('cuerpo_publicacion', models.TextField(max_length=5500)),
                ('palabras', models.BigIntegerField(editable=False)),
                ('dias_de_publicacion', models.IntegerField()),
                ('sellos', models.IntegerField()),
                ('cuil', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('archivo', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
