# Generated by Django 5.0 on 2024-01-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('inicado', 'iniciado'), ('pendiente_pago', 'pendiente_pago'), ('pendiente_revision_pago', 'pendiente_revision_pago'), ('aprobado', 'aprobado'), ('publicado', 'publicado'), ('rechazado', 'rechazado')], default='iniciado', max_length=23),
        ),
    ]
