# Generated by Django 5.0 on 2024-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_alter_publicacion_archivo_alter_publicacion_cuil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='cantidad_de_copias',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='copias_requeridas',
            field=models.BooleanField(default=False),
        ),
    ]
